version: '2'
services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB:users
      - POSTGRES_HOST_AUTH_METHOD:trust
    ports:
      - "5433:5433"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data