# Generated by Django 4.1.1 on 2022-09-15 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('category', models.CharField(blank=True, choices=[('cafe', 'cafe'), ('restaurant', 'restaurant'), ('coffe house', 'coffe house'), ('pub', 'pub'), ('bar', 'bar'), ('food courts', 'food courts'), ('other', 'other')], default='cafe', max_length=20, null=True)),
                ('kitchen', models.CharField(blank=True, choices=[('asian', 'asian'), ('american', 'american'), ('national', 'national'), ('vegeterian', 'vegeterian'), ('other', 'other')], default=None, max_length=20, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
