# Generated by Django 4.1.1 on 2022-09-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
